"""Changed to AGENTS

Revision ID: ab71638bf1be
Revises: 70560954af5c
Create Date: 2025-10-31 14:08:43.954075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab71638bf1be'
down_revision: Union[str, Sequence[str], None] = '70560954af5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=5000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=25000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=25000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###
